import { Component, Input, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'ngx-sunview',
  styleUrls: [
    '../../../../node_modules/suneditor/src/assets/css/suneditor-contents.css',
  ],
  encapsulation: ViewEncapsulation.None,
  template: `
    <div
      class="sun-editor-editable"
      *ngIf="bypassSantiziser"
      [innerHTML]="content | safeHtml"
    ></div>
    <div
      class="sun-editor-editable"
      *ngIf="!bypassSantiziser"
      [innerHTML]="content"
    ></div>
  `,
})
export class NgxSunViewComponent {
  /**
   * HTML content generated by the editor to display
   */
  @Input() content: string;

  /**
   * Bypass angular's DomSanitizer
   * @default false
   */
  @Input() bypassSantiziser: boolean = false;
}
